env:
  GF_AUTH_DISABLE_LOGIN_FORM: "true"
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
datasources:
  datasources.yaml:
    apiVersion: 1

    datasources:
      - name: Loki
        type: loki
        url: http://loki:3100
        uid: loki_datasource
        jsonData:
          derivedFields:
            - datasourceUid: tempo_datasource
              matcherRegex: "\"traceID\":\"([a-z0-9]*)\""
              name: TraceID
              url: '$${__value.raw}'
      - name: Tempo
        type: tempo
        url: http://tempo:3100
        uid: tempo_datasource