curDir = os.path.join(os.path.dirname(__file__), "..", "..")

v1alpha1.extension_repo(name='tilt-grafana', url='file://'+curDir)
v1alpha1.extension(name='tilt-grafana', repo_name='tilt-grafana', repo_path='')
load('ext://tilt-grafana', 'grafana_compose', 'metrics_endpoint')

endpoints = grafana_compose(
    metrics_endpoints=[
        metrics_endpoint(name='generator', port=2112)
    ],
    dashboard_files=['../dashboards/example.json']
)

local_resource(
    "generator",
    serve_cmd="go run ../generator",
    serve_env={
        "OTEL_OTLP_HTTP_ENDPOINT": endpoints.otlp_http,
    },
    links=[link("http://localhost:2112/metrics", "Metrics")],
    labels=["generator"]
)
