curDir = os.path.join(os.path.dirname(__file__), "..", "..")

v1alpha1.extension_repo(name='tilt-grafana', url='file://'+curDir)
v1alpha1.extension(name='tilt-grafana', repo_name='tilt-grafana', repo_path='')
load('ext://tilt-grafana', 'grafana_compose')

grafana_compose()

local_resource(
    "generator",
    serve_cmd="OTEL_OTLP_HTTP_ENDPOINT=localhost:4318 go run ../generator"
)