---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: grafana
    component: grafana-datasources
data:
  grafana-datasources: |
    apiVersion: 1
    datasources:
        - name: Tempo
          type: tempo
          url: http://tempo:3200