apiVersion: v1
kind: Service
metadata:
  name: mimir
  labels:
    app: mimir
    job: mimir
  annotations:
   prometheus.io/port: "9009"
   prometheus.io/scrape: "true" 
spec:
  ports:
  - port: 9009
    protocol: TCP
  selector:
    app: mimir