env:
  GF_AUTH_DISABLE_LOGIN_FORM: "true"
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  GF_FEATURE_TOGGLES_ENABLE: "flameGraph"
  GF_DIAGNOSTICS_PROFILING_ENABLED: "true"
  GF_DIAGNOSTICS_PROFILING_ADDR: "0.0.0.0"
  GF_DIAGNOSTICS_PROFILING_PORT: "6060"

podAnnotations:
  phlare.grafana.com/scrape: "true"
  phlare.grafana.com/port: "6060"

datasources:
  datasources.yaml:
    apiVersion: 1

    datasources:
      - name: Loki
        type: loki
        url: http://loki:3100
        uid: loki_datasource
        jsonData:
          derivedFields:
            - datasourceUid: tempo_datasource
              matcherRegex: "\"traceID\":\"([a-z0-9]*)\""
              name: TraceID
              url: '$${__value.raw}'
      - name: Tempo
        type: tempo
        url: http://tempo:3100
        uid: tempo_datasource
      - name: Mimir
        type: prometheus
        url: http://mimir:9009/prometheus
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
      - name: Phlare
        type: phlare
        uid: phlare
        url: http://phlare:4100/

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: "grafana-dashboard-config"