curDir = os.path.join(os.path.dirname(__file__), "..", "..")

v1alpha1.extension_repo(name='tilt-grafana', url='file://'+curDir)
v1alpha1.extension(name='tilt-grafana', repo_name='tilt-grafana', repo_path='')
load('ext://tilt-grafana', 'grafana_kubernetes')

grafana_kubernetes()

load("../generator/Tiltfile", "generator_kubernetes")
generator_kubernetes()