name: TEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.8'
      - uses: azure/setup-helm@v3
        with:
          version: 'v3.9.0'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Install tilt
        run: curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
      - name: Run tilt
        run: tilt ci
        working-directory: test/kubernetes
  compose:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.8'
      - uses: azure/setup-helm@v3
        with:
          version: 'v3.9.0'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Install tilt
        run: curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
      - name: Run tilt
        run: tilt ci
        working-directory: test/compose